plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0.24,6.2)'
    id 'org.spongepowered.mixin' version '0.7.38'
}

version = '1.0.0'
group = 'com.voidlessstar'

base {
    archivesName = 'VoidUI-forge-1.20.1'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'mixin.debug.dump', 'true'
            mods {
                modtitle {
                    source sourceSets.main
                }
            }
        }
        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                modtitle {
                    source sourceSets.main
                }
            }
        }
        data {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            args '--mod', 'modtitle', '--all', '--output', file('src/generated/resources/'), '--existing', file('src/main/resources/')
            mods {
                modtitle {
                    source sourceSets.main
                }
            }
        }
    }
}

repositories {
    maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
    maven { url = uri("file://${project.projectDir}/repo") }
}

dependencies {
    minecraft "net.minecraftforge:forge:1.20.1-47.3.0"
    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
    implementation fg.deobf('caxton:caxton:0.6.4')
    jarJar('caxton:caxton:[0.6.4,0.6.5)')
    implementation fg.deobf('biaohealthbarx:biaohealthbarx:0.1.0')
    jarJar('biaohealthbarx:biaohealthbarx:[0.1.0,0.2)')
}

mixin {
    add sourceSets.main, 'modtitle.refmap.json'
    config 'modtitle.mixins.json'
}

jar {
    manifest {
        attributes([
                "Specification-Title"     : "modtitle",
                "Specification-Version"   : "1",
                "Implementation-Title"    : project.name,
                "Implementation-Version"  : project.version,
                "Implementation-Vendor"   : "voidlessstar"
        ])
    }
}

jar.finalizedBy('reobfJar')

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/mcmodsrepo"
        }
    }
}
