modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="modtitle"
version="1.0.0"
displayName="VoidUI"
logoFile="voidui.png"
credits="VoidLessStar"
description='''VoidUI by VoidLessStar - ปรับหน้าไตเติล โลโก้ ฟอนต์ไทย และเครดิตมอดทุกตัวในแพ็ก'''

[[dependencies.modtitle]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="CLIENT"

[[dependencies.modtitle]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21)"
ordering="NONE"
side="CLIENT"
